# Generated by Django 2.1.5 on 2019-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190128_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, default='avatar/avatar-5.png', null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='avatar/avatar-2.png', null=True, upload_to='profile_image'),
        ),
    ]
