# Generated by Django 2.1.5 on 2019-01-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190129_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa_de_apoio',
            name='foto',
            field=models.ImageField(blank=True, default='gallary/casa-de-apoio.jpg', null=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='casa_de_apoio',
            name='telefone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
