# Generated by Django 2.1.5 on 2019-01-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190129_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa_de_apoio',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='casa_de_apoio',
            name='telefone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
