# Generated by Django 2.1.5 on 2019-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190129_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteDeReflexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReflexoPatelarESQ', models.CharField(choices=[('NORMAL', 'Normal'), ('DIMINUIDO', 'Diminuido')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='visita',
            name='dx',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='pa',
        ),
    ]
