# Generated by Django 2.1.5 on 2019-01-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190129_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testedereflexo',
            name='ReflexoPatelarESQ',
        ),
        migrations.AddField(
            model_name='testedereflexo',
            name='reflexoPatelarESQ',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('DIMINUIDO', 'Diminuido')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testedereflexo',
            name='visita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Visita'),
        ),
    ]
