# Generated by Django 2.1.5 on 2019-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190129_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testedereflexo',
            name='visita',
        ),
        migrations.AddField(
            model_name='visita',
            name='GetUpAndGo',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Equilibrio Alterado', 'Equilibrio Alterado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='altura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordCalcanharJoelho',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordDiadococinesia',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordIdxIdx',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordIdxIdxOpen',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordIdxNaz',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='cordIdxNazOpen',
            field=models.CharField(blank=True, choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='estesiometroMaos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='estesiometroPeDireito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='estesiometroPeEsquerdo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='glicemia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='imc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='pa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='reflexoPatelarDireito',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Diminuido', 'Diminuido')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='reflexoPatelarEsquerdo',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Diminuido', 'Diminuido')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='reflexoTricipitalDireito',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Diminuido', 'Diminuido')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='reflexoTricipitalEsquedo',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Diminuido', 'Diminuido')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='tinetti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TesteDeReflexo',
        ),
    ]
