# Generated by Django 2.1.5 on 2019-03-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190202_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa_de_apoio',
            name='foto',
            field=models.ImageField(blank=True, default='images/gallary/casa-de-apoio.jpg', null=True, upload_to='static/images/profile_image'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Casa_de_Apoio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, default='images/avatar/avatar-5.png', null=True, upload_to='images/profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='images/avatar/avatar-2.png', null=True, upload_to='static/images/profile_image'),
        ),
    ]
