# Generated by Django 2.1.5 on 2019-03-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190301_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa_de_apoio',
            name='foto',
            field=models.ImageField(blank=True, default='images/gallary/casa-de-apoio.jpg', null=True, upload_to='images/profile_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='images/avatar/avatar-2.png', null=True, upload_to='images/profile_image'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Paciente'),
        ),
    ]
